### ISSUE TITLE
Podfile points to non-existent location

### ISSUE THREAD

**Issue by rosen-vladimirov** [vcooley/nativescript-input-mask#2]
This line:
https://github.com/vcooley/nativescript-input-mask/blob/372a6b205b86f1c1a17c61dc1240731ff3dd6d29/src/platforms/ios/Podfile#L1

points that the Pod should be taken from local directory. However, this directory is not a common one and maybe a version should stay there.
This breaks the usage of the plugin in NativeScript as the plugin fails to install correctly and breaks the preparation of iOS project.

**Comment by vcooley** [comment]
I ended up making some changes to the native dependency to get everything exposed to the Objective-C runtime. I'll see what I can do to fix it when I get a chance. In the meantime anyone wanting to use this plugin can unzip this to `~/Projects/input-mask-ios`
[input-mask-ios.zip](https://github.com/vcooley/nativescript-input-mask/files/2095755/input-mask-ios.zip)
